name: Help Me NCRI

title: Help Me NCRI
description: Shortcuts to get help with your research

version: v0.2

baseurl: ""
permalink: /:slug/
logo: /assets/logo.png

theme: 

plugins:
  - jekyll-redirect-from
  - jekyll-remote-theme

remote_theme: jonaharagon/jekyll-bootstrap-theme

collections:
  urls:
    output: true
    permalink: /:slug

whitelist:
  - jekyll-redirect-from

redirect_from:
  json: false

include:
  - _urls

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
